### ISSUE TITLE
add missing tests for deepCopyAdded, deepAssignAdded

### ISSUE THREAD

**Issue by GrosSacASac** [GrosSacASac/utilsac#11]

**Comment by geekyrajshri** [comment]
i would like to try this.

**Comment by GrosSacASac** [comment]
ok

**Comment by GrosSacASac** [comment]
are you still on it ?

**Comment by geekyrajshri** [comment]
yes, I will try to complete that today

**Comment by geekyrajshri** [comment]
Hi @GrosSacASac 
I am getting this issue while pushing.

ERROR: Permission to GrosSacASac/utilsac.git denied to geekyrajshri.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

**Comment by GrosSacASac** [comment]
Most likely you don't have permission to push to GrosSacASac/utilsac.git. Instead you should make a fork.

Full instructions https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/
