### ISSUE TITLE
add deepEqualAdded

### ISSUE THREAD

**Issue by GrosSacASac** [GrosSacASac/utilsac#18]
Similar to deepEqual which should work with RegExp, Date, Map, Set and Typed Arrays

**Comment by mishabruml** [comment]
could you spec this out a bit more?

**Comment by GrosSacASac** [comment]
I will add some (failing) tests

**Comment by GrosSacASac** [comment]
I added some tests that should pass
https://github.com/GrosSacASac/utilsac/blob/master/tests/specification/deepEqual.js#L194

**Comment by GrosSacASac** [comment]
I added a placeholder inside deep.js

Are you still working on it ?

**Comment by jmeline** [comment]
If @mishabruml isn't interested in doing this, I have a working implementation of this that I can submit for approval. As it's your call @GrosSacASac, I don't want to overstep someone else giving it a shot.

**Comment by GrosSacASac** [comment]
Yes, please do

**Comment by GrosSacASac** [comment]
@jmeline I added you so you can push directly

**Comment by jmeline** [comment]
Thanks @GrosSacASac, I put out a PR for feedback but I can merge it immediately if you prefer.
