### ISSUE TITLE
add deepDifference

### ISSUE THREAD

**Issue by GrosSacASac** [GrosSacASac/utilsac#32]
It should return the difference between two objects. Split into 3 categories, added, removed and changed. For example:
```js
const a = {
    same: 7,
    x: 30,
    w: 20,
    deep: {},
};

const b = {
    same: 7,
    x: 15,
    z: 10,
    deep: {
        deeper: 99,
    },
};

const difference = deepDifference(a, b);

deepEqual(difference, {
    add: [
        {
            name: ['z'],
            value: 10,
        },
        {
            name: ['deep', 'deeper'],
            value: 99,
        },
    ],
    remove: [
        {
            name: ['w'],
            value: 20,
        },
    ],
    change: [
        {
            name: ['x'],
            oldValue: 30,
            newValue: 15,
        },
    ],
});
```

**Comment by Raene** [comment]
From your example, Add category contains keys found in object B but not in Obj A. Why does the Deep key appear under Add? Shouldn't i be under change category, since it's a key that appears in both objects but with a different value.

**Comment by GrosSacASac** [comment]
Think recursively.
what would deepDifference(a.deep, b.deep); give
same except the name array would be just 'deeper'

**Comment by Raene** [comment]
So the difference is in their value right?
Which makes it a change?

**Comment by GrosSacASac** [comment]
it is a change from the top level perspective,
and an addition from the object inside perspective,

**Comment by Raene** [comment]
Oh. I see now.
it is a change from the top level perspective,
and an addition from the object inside perspective,
